import type { CuratedSection } from '@/lib/types'

export const CURATED_SECTIONS: Omit<CuratedSection, 'markets'>[] = [
  {
    id: 'iran',
    label: 'The Iran Conflict',
    intro: 'The US-Israeli military campaign against Iran is the single largest cluster of prediction market activity. Over $100M in volume concentrated on conflict timelines, regime change, and the Strait of Hormuz.',
    narrative: 'Markets are pricing roughly 1-in-3 odds the conflict winds down near-term, with high uncertainty around regime change and escalation persisting through summer.',
    slugs: [
      'will-the-iranian-regime-fall-by-the-end-of-2026',
      'will-the-iranian-regime-fall-by-june-30',
      'will-the-iranian-regime-fall-by-march-31',
      'will-the-us-invade-iran-before-2027',
      'will-the-us-invade-iran-by-march-31',
      'will-the-iranian-regime-survive-us-military-strikes-741',
      'iran-nuke-before-2027',
      'iran-nuclear-test-before-2027',
      'us-iran-nuclear-deal-before-2027',
      'us-iran-nuclear-deal-by-march-31',
      'us-iran-nuclear-deal-by-june-30',
      'will-iran-withdraw-from-the-npt-before-2027',
      'iran-coup-attempt-by-june-30',
      'will-the-us-reopen-its-embassy-in-iran-in-2026',
    ],
    spotlightSlug: 'will-the-iranian-regime-fall-by-the-end-of-2026',
    spotlightDescription: 'The headline question on regime survival. Markets reflect significant uncertainty about whether the current Iranian government survives through end of 2026.',
  },
  {
    id: '2028',
    label: '2028 Presidential Race',
    intro: 'Over $1.5B in combined volume on the 2028 race. JD Vance leads the Republican field while Gavin Newsom is the Democratic frontrunner — but wide-open fields mean high uncertainty.',
    narrative: 'Markets are treating 2028 as wide open. No candidate commands majority probability — the spread signals high uncertainty this far out.',
    slugs: [
      'will-jd-vance-win-the-2028-us-presidential-election',
      'will-gavin-newsom-win-the-2028-us-presidential-election',
      'will-the-republicans-win-the-2028-us-presidential-election',
      'will-the-democrats-win-the-2028-us-presidential-election',
      'will-jd-vance-win-the-2028-republican-presidential-nomination',
      'will-marco-rubio-win-the-2028-republican-presidential-nomination',
      'will-gavin-newsom-win-the-2028-democratic-presidential-nomination-568',
      'will-alexandria-ocasio-cortez-win-the-2028-democratic-presidential-nomination-653',
    ],
    spotlightSlug: 'will-jd-vance-win-the-2028-us-presidential-election',
    spotlightDescription: 'The headline market. JD Vance holds a slim lead over Gavin Newsom in the overall presidential market.',
  },
  {
    id: 'midterms',
    label: '2026 Midterms',
    intro: 'Control of the House and Senate hangs in the balance.',
    narrative: 'Markets give Democrats a slight edge to retake the House, while the Senate landscape favors Republicans defending fewer seats.',
    slugs: [
      'will-the-democratic-party-control-the-house-after-the-2026-midterm-elections',
      'will-the-republican-party-control-the-house-after-the-2026-midterm-elections',
      'will-the-democratic-party-control-the-senate-after-the-2026-midterm-elections',
      'will-the-republican-party-control-the-senate-after-the-2026-midterm-elections',
      '2026-balance-of-power-d-senate-d-house-949',
      '2026-balance-of-power-r-senate-r-house-537',
      '2026-balance-of-power-d-senate-r-house-692',
      '2026-balance-of-power-r-senate-d-house-444',
    ],
    spotlightSlug: 'will-the-democratic-party-control-the-house-after-the-2026-midterm-elections',
    spotlightDescription: 'The marquee House control question. Democrats need a net gain to flip the chamber from Republican control.',
  },
  {
    id: 'executive',
    label: 'Executive Branch',
    intro: 'Markets on Trump approval, cabinet stability, and the Federal Reserve.',
    narrative: 'The Fed Chair confirmation market is effectively decided. Cabinet departure risk by end of March sits at 90%.',
    slugs: [
      'will-trump-be-impeached-by-december-31-2026',
      'will-trump-resign-by-december-31-2026',
      'trump-removed-via-25th-amendment-before-2027',
      'trump-out-as-president-before-2027',
      'will-trump-repeal-presidential-term-limits-in-2026',
      'will-trump-try-to-fire-powell-by-march-31',
      'will-trump-sue-powell-by-march-31',
      'jerome-powell-federally-charged-by-june-30',
      'will-elon-musk-rejoin-the-trump-administration-in-2026',
      'will-trump-acquire-greenland-before-2027',
    ],
    spotlightSlug: 'trump-out-as-president-before-2027',
    spotlightDescription: 'The aggregate question on whether Trump completes his second term. Markets price this as highly likely.',
  },
  {
    id: 'trade',
    label: 'Trade War & Tariffs',
    intro: 'The 10% blanket tariff is expected to remain. China tariffs have come down from 2025 highs.',
    narrative: 'The 10% blanket tariff is near-certain to persist. Markets see Mexico and India as most likely trade deal candidates.',
    slugs: [
      'will-a-10-us-blanket-tariff-be-in-effect-on-march-31',
      '100-tariff-on-canada-in-effect-by-june-30',
      'tariff-increase-on-canada-in-effect-by-june-30',
      'will-the-court-force-trump-to-refund-tariffs-2026-06-30',
      'will-congress-pass-any-tariffs-by-march-31',
      'will-trump-create-a-tariff-dividend-by-june-30',
      'will-trump-visit-china-by-march-31',
      'will-trump-cut-off-trade-with-spain',
    ],
    spotlightSlug: 'will-a-10-us-blanket-tariff-be-in-effect-on-march-31',
    spotlightDescription: 'The near-term tariff status check. Markets price the 10% blanket tariff as near-certain to remain in place.',
  },
  {
    id: 'legislation',
    label: 'Legislation',
    intro: 'Key legislative priorities in Congress.',
    narrative: 'Markets give low odds to major legislation this year. Executive action continues to dominate.',
    slugs: [
      'will-trump-end-department-of-education-before-2027',
      'will-trump-cut-corporate-taxes-before-2027',
      'will-trump-cut-long-term-capital-gains-tax-before-2027',
      'will-trump-reduce-the-deficit-before-2027',
      'will-trump-nationalize-elections',
    ],
    spotlightSlug: 'will-trump-end-department-of-education-before-2027',
    spotlightDescription: 'One of the marquee legislative battles. Markets price this as unlikely to fully resolve within the current Congress.',
  },
  {
    id: 'economy',
    label: 'Economy',
    intro: 'Recession odds, Fed rate decisions, and economic indicators.',
    narrative: 'Markets price three consecutive Fed pauses at 55%. Recession probability has climbed but remains below 50%.',
    slugs: [
      'us-recession-by-end-of-2026',
      'canada-recession-before-2027',
      'will-no-fed-rate-cuts-happen-in-2026',
      'will-1-fed-rate-cut-happen-in-2026',
      'will-2-fed-rate-cuts-happen-in-2026',
      'will-3-fed-rate-cuts-happen-in-2026',
      'fed-rate-hike-in-2026',
      'fed-emergency-rate-cut-before-2027',
    ],
    spotlightSlug: 'us-recession-by-end-of-2026',
    spotlightDescription: 'The headline recession market. Probability has risen alongside tariff escalation but remains below 50%.',
  },
  {
    id: 'primaries',
    label: 'State Primaries',
    intro: 'Key gubernatorial and Senate primary races shaping the 2026 map.',
    narrative: 'Several competitive primaries will define the general election landscape in key swing states.',
    slugs: [
      'will-ken-paxton-win-the-2026-republican-primary',
      'will-john-cornyn-win-the-2026-republican-primary',
      'will-mallory-mcmorrow-win-the-2026-michigan-democratic-primary',
      'will-haley-stevens-win-the-2026-michigan-democratic-primary',
      'will-dana-nessel-win-the-2026-michigan-democratic-primary',
      'will-rick-caruso-win-the-california-governor-election-in-2026',
      'will-katie-porter-win-the-california-governor-election-in-2026',
      'will-jared-golden-be-the-democratic-nominee-for-senate-in-maine',
      'will-lindsey-graham-be-the-republican-nominee-for-senate-in-south-carolina',
    ],
    spotlightSlug: 'will-ken-paxton-win-the-2026-republican-primary',
    spotlightDescription: 'The Texas Senate primary is among the most watched — a contest between Paxton and Cornyn signals the direction of the GOP.',
  },
]
